// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { GatewayStatus } from "./GatewayStatus";
import type { ToolKind } from "./ToolKind";

export type AdapterHealth = { tool: ToolKind, mode: string, online: boolean, gatewayStatus: GatewayStatus | null, gatewayDetail: string | null, lastSuccessAt: string | null, lastErrorAt: string | null, lastError: string | null, freshness: Freshness, };
