// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolKind } from "./ToolKind";

export type AppConfig = { listenHost: string, listenPort: number, historyDays: number, companionEnabled: boolean, localIp: string | null, disabledSources: Array<ToolKind>, hiddenSources: Array<ToolKind>, };
