// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ArtifactRef = { id: string, kind: string, path: string | null, preview: string | null, digest: string | null, createdAt: string, };
