// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolKind } from "./ToolKind";

export type AttentionItem = { id: string, tool: ToolKind, runId: string | null, severity: string, kind: string, title: string, detail: string | null, since: string, };
