// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdapterHealth } from "./AdapterHealth";
import type { AppConfig } from "./AppConfig";
import type { AttentionItem } from "./AttentionItem";
import type { CommitRecord } from "./CommitRecord";
import type { CompletionRecord } from "./CompletionRecord";
import type { IdentityState } from "./IdentityState";
import type { PendingCron } from "./PendingCron";
import type { RunRecord } from "./RunRecord";
import type { UsageBucket } from "./UsageBucket";

export type BootstrapPayload = { generatedAt: string, runs: Array<RunRecord>, attentions: Array<AttentionItem>, usageBuckets: Array<UsageBucket>, commits: Array<CommitRecord>, identities: Array<IdentityState>, adapterHealth: Array<AdapterHealth>, recentCompletions: Array<CompletionRecord>, pendingCrons: Array<PendingCron>, config: AppConfig, };
