// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuditLevel } from "./AuditLevel";
import type { CapabilityFailureMode } from "./CapabilityFailureMode";
import type { CapabilitySource } from "./CapabilitySource";
import type { SchemaConfidence } from "./SchemaConfidence";

export type CapabilityDescriptor = { id: string, source: CapabilitySource, confidence: SchemaConfidence, mutatesState: boolean, requiresUserConfirmation: boolean, requiresManagedProcess: boolean, canExposeSecrets: boolean, auditLevel: AuditLevel, failureMode: CapabilityFailureMode, };
