// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitAttributionMethod } from "./CommitAttributionMethod";
import type { SourceConfidence } from "./SourceConfidence";
import type { ToolKind } from "./ToolKind";

export type CommitAttributionLink = { runId: string, tool: ToolKind, sourceMode: string, projectName: string, sessionLabel: string, score: number, allocatedTokens: number, allocatedCostUsd: number | null, confidence: SourceConfidence, method: CommitAttributionMethod, };
