// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitAttributionLink } from "./CommitAttributionLink";
import type { CommitAttributionMethod } from "./CommitAttributionMethod";
import type { CommitSourceStat } from "./CommitSourceStat";
import type { SourceConfidence } from "./SourceConfidence";

export type CommitRecord = { id: string, repoId: string, repoName: string, repoRoot: string, worktreeId: string | null, worktreeName: string | null, sha: string, shortSha: string, authorName: string, committedAt: string, summary: string, filesChanged: number, insertions: number, deletions: number, attributedTokens: number, attributedCostUsd: number | null, runCount: number, sourceCount: number, confidence: SourceConfidence, method: CommitAttributionMethod, sources: Array<CommitSourceStat>, links: Array<CommitAttributionLink>, };
