// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceConfidence } from "./SourceConfidence";
import type { ToolKind } from "./ToolKind";

export type CommitSourceStat = { tool: ToolKind, runCount: number, attributedTokens: number, attributedCostUsd: number | null, confidence: SourceConfidence, };
