// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitRecord } from "./CommitRecord";
import type { HistoryRange } from "./HistoryRange";
import type { RunRecord } from "./RunRecord";

export type CommitHistoryPayload = { generatedAt: string, range: HistoryRange, truncated: boolean, runs: Array<RunRecord>, commits: Array<CommitRecord>, };
