// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolKind } from "./ToolKind";

export type CompletionRecord = { id: string, tool: ToolKind, projectName: string, title: string, finishedAt: string, durationMs: number, totalTokens: number | undefined, costUsd: number | null, state: string, summary: string | null, };
