// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionMode } from "./CompletionMode";

export type CompletionPolicy = { mode: CompletionMode, requiredArtifacts: Array<string>, };
