// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataSourceError } from "./DataSourceError";
import type { DataSourceType } from "./DataSourceType";
import type { SchemaConfidence } from "./SchemaConfidence";

export type DataSourceHealth = { id: string, sourceType: DataSourceType, path: string | null, apiEndpoint: string | null, lastSeenAt: string | null, schemaVersion: string | null, schemaConfidence: SchemaConfidence, errors: Array<DataSourceError>, };
