// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceConfidence } from "./SourceConfidence";
import type { ToolKind } from "./ToolKind";

export type IdentityState = { tool: ToolKind, authMode: string | null, provider: string | null, accountAlias: string | null, fingerprint: string | null, authAge: string | null, verified: boolean, configured: boolean, source: SourceConfidence, };
