// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JumpReliability } from "./JumpReliability";
import type { JumpTargetKind } from "./JumpTargetKind";
import type { TerminalTarget } from "./TerminalTarget";

export type JumpTarget = { kind: JumpTargetKind, label: string, command: Array<string> | null, cwd: string | null, url: string | null, terminal: TerminalTarget | null, reliability: JumpReliability, requiresConfirmation: boolean, };
