// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LaunchSpec = { model: string | null, timeoutSecs: number | undefined, allowedTools: Array<string>, args: Array<string>, };
