// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactSpec } from "./ArtifactSpec";

export type LaunchPreview = { renderedPrompt: string, inputArtifacts: Array<ArtifactSpec>, model: string | null, allowedTools: Array<string>, estimatedPromptChars: number, };
