// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkConfidence } from "./LinkConfidence";

export type LinkedRunRef = { runId: string, confidence: LinkConfidence, matchedBy: string, linkedAt: string, };
