// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceConfidence } from "./SourceConfidence";

export type MoneyValue = { usd: number | null, confidence: SourceConfidence, };
