// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceConfidence } from "./SourceConfidence";

export type QuotaValue = { fiveHourUsedPct: number | null, sevenDayUsedPct: number | null, resetAt: Array<string>, confidence: SourceConfidence, };
