// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvertisedAddress } from "./AdvertisedAddress";
import type { RemoteAccessMode } from "./RemoteAccessMode";
import type { RemoteDevice } from "./RemoteDevice";
import type { RemotePairingCode } from "./RemotePairingCode";

export type RemoteAccessState = { enabled: boolean, mode: RemoteAccessMode, listenerHost: string, listenerPort: number, addresses: Array<AdvertisedAddress>, devices: Array<RemoteDevice>, pendingPairings: Array<RemotePairingCode>, };
