// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteDevice = { id: string, label: string, pairedAt: string, lastSeenAt: string | null, expiresAt: string, };
