// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityDescriptor } from "./CapabilityDescriptor";
import type { DataSourceHealth } from "./DataSourceHealth";
import type { JumpTarget } from "./JumpTarget";
import type { MoneyValue } from "./MoneyValue";
import type { QuotaValue } from "./QuotaValue";
import type { RunState } from "./RunState";
import type { SessionLifecycle } from "./SessionLifecycle";
import type { SourceInfo } from "./SourceInfo";
import type { TokenUsage } from "./TokenUsage";
import type { ToolKind } from "./ToolKind";
import type { UsageSemantics } from "./UsageSemantics";
import type { VcsContext } from "./VcsContext";

export type RunRecord = { id: string, tool: ToolKind, sourceId?: string, sourceMode: string, projectName: string, workspacePath: string, workspaceShort: string, model: string | null, provider: string | null, agentName: string | null, agentDisplayName: string | null, accountAlias: string | null, authMode: string | null, authVerified: boolean, sessionId: string | null, threadId: string | null, sessionKey: string | null, transcriptPath: string | null, startedAt: string, lastActivityAt: string, elapsedMs: number, state: RunState, lastAction: string | null, lastTail: string | null, pendingApproval: boolean, firstQuestion: string | null, lastQuestion: string | null, errorMessage: string | null, messageCount: number, tokens: TokenUsage, cost: MoneyValue, quota: QuotaValue, source: SourceInfo, lifecycle?: SessionLifecycle, usageSemantics?: UsageSemantics, dataSources?: Array<DataSourceHealth>, capabilities?: Array<CapabilityDescriptor>, jumpTargets?: Array<JumpTarget>, toolSpecific?: Record<string, unknown>, vcs: VcsContext | null, originLabel: string | null, originProvider: string | null, };
