// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoneyValue } from "./MoneyValue";
import type { QuotaValue } from "./QuotaValue";
import type { RunState } from "./RunState";
import type { SourceInfo } from "./SourceInfo";
import type { TokenUsage } from "./TokenUsage";
import type { ToolKind } from "./ToolKind";
import type { VcsContext } from "./VcsContext";
import type { WorkflowHint } from "./WorkflowHint";

export type RunRecord = { id: string, tool: ToolKind, sourceMode: string, projectName: string, workspacePath: string, workspaceShort: string, model: string | null, provider: string | null, agentName: string | null, agentDisplayName: string | null, accountAlias: string | null, authMode: string | null, authVerified: boolean, sessionId: string | null, threadId: string | null, sessionKey: string | null, transcriptPath: string | null, startedAt: string, lastActivityAt: string, elapsedMs: number, state: RunState, lastAction: string | null, lastTail: string | null, pendingApproval: boolean, firstQuestion: string | null, lastQuestion: string | null, errorMessage: string | null, messageCount: number, tokens: TokenUsage, cost: MoneyValue, quota: QuotaValue, source: SourceInfo, vcs: VcsContext | null, 
/**
 * Human-readable session origin, e.g. "Telegram: Yixiao Wang", "Cron: AI Daily Brief"
 */
originLabel: string | null, 
/**
 * Source provider type, e.g. "telegram", "cron", "heartbeat"
 */
originProvider: string | null, 
/**
 * Workflow hint from context file, ingest, or prompt marker
 */
workflowHint: WorkflowHint | null, };
