// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LifecycleStatusSource } from "./LifecycleStatusSource";
import type { RunState } from "./RunState";

export type SessionLifecycle = { status: RunState, statusSource: LifecycleStatusSource, startedAt: string | null, lastActivityAt: string | null, endedAt: string | null, error: string | null, };
