// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Freshness } from "./Freshness";
import type { SourceConfidence } from "./SourceConfidence";

export type SourceInfo = { confidence: SourceConfidence, freshness: Freshness, lastUpdatedAt: string, };
