// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactExpectation } from "./ArtifactExpectation";
import type { ArtifactSpec } from "./ArtifactSpec";
import type { CompletionPolicy } from "./CompletionPolicy";
import type { LaunchSpec } from "./LaunchSpec";
import type { ToolKind } from "./ToolKind";
import type { WorkflowStepKind } from "./WorkflowStepKind";

export type StepDef = { id: string, order: number, label: string, tool: ToolKind, kind: WorkflowStepKind, promptTemplate: string | null, inputs: Array<ArtifactSpec>, outputs: Array<ArtifactExpectation>, approvalRequired: boolean, autoAdvanceEligible: boolean, completion: CompletionPolicy, launch: LaunchSpec | null, };
