// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactRef } from "./ArtifactRef";
import type { CompletionSource } from "./CompletionSource";
import type { LinkedRunRef } from "./LinkedRunRef";
import type { StepRunState } from "./StepRunState";
import type { ToolKind } from "./ToolKind";
import type { WorkflowStepKind } from "./WorkflowStepKind";

export type StepRun = { stepId: string, order: number, label: string, tool: ToolKind, kind: WorkflowStepKind, state: StepRunState, promptRendered: string | null, linkedRuns: Array<LinkedRunRef>, artifacts: Array<ArtifactRef>, completionSource: CompletionSource | null, startedAt: string | null, completedAt: string | null, error: string | null, };
