// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalProvider = "warp" | "iTerm2" | "ghostty" | "terminalApp" | "vsCode" | "cursor" | "tmux";
