// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalProvider } from "./TerminalProvider";

export type TerminalTarget = { provider: TerminalProvider, windowId: string | null, tabId: string | null, paneId: string | null, pid: number | null, };
