// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolKind = "claude" | "codex" | "openClaw" | "hermes" | "codeBuddy" | "gemini" | "pi" | "openCode" | "copilot" | "openHands" | "continueCn" | "qwen" | "kimi" | "goose" | "cursor" | "cline" | "kiro" | "workBuddy" | "amazonQ" | "aider" | "amp" | "windsurf" | "codebuff" | "roo" | "kilo";
