// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceConfidence } from "./SourceConfidence";

export type UsageBucket = { scope: Record<string, string>, window: string, start: string, end: string, inputTokens: number, outputTokens: number, cacheReadTokens: number, cacheWriteTokens: number, totalTokens: number, costUsd: number | null, confidence: SourceConfidence, };
