// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageCostKind } from "./UsageCostKind";
import type { UsageDataSource } from "./UsageDataSource";

export type UsageSemantics = { costKind: UsageCostKind, source: UsageDataSource, entersUsageTotals: boolean, note: string | null, };
