// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryRange } from "./HistoryRange";
import type { RunRecord } from "./RunRecord";
import type { UsageBucket } from "./UsageBucket";

export type UsageHistoryPayload = { generatedAt: string, range: HistoryRange, truncated: boolean, runs: Array<RunRecord>, usageBuckets: Array<UsageBucket>, };
