// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceConfidence } from "./SourceConfidence";

export type VcsContext = { repoId: string, repoName: string, repoRoot: string, worktreeId: string | null, worktreeName: string | null, worktreePath: string | null, branch: string | null, confidence: SourceConfidence, };
