// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowExecutionMode } from "./WorkflowExecutionMode";
import type { WorkflowRunState } from "./WorkflowRunState";

export type WorkflowRunSummary = { id: string, workflowId: string, workflowName: string, state: WorkflowRunState, executionMode: WorkflowExecutionMode, progressLabel: string, currentStep: string | null, waitingCount: number, updatedAt: string, };
