// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow metadata attached to a run, discovered via context file, ingest hint, or prompt marker.
 */
export type WorkflowHint = { workflowId: string | null, stepId: string | null, parentStepId: string | null, artifactRefs: Array<string>, updatedAt: string | null, };
