// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepDef } from "./StepDef";

export type WorkflowDef = { id: string, name: string, description: string | null, defaultWorkingDir: string | null, steps: Array<StepDef>, createdAt: string, updatedAt: string, };
