// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepRun } from "./StepRun";
import type { WorkflowDef } from "./WorkflowDef";
import type { WorkflowExecutionMode } from "./WorkflowExecutionMode";
import type { WorkflowRunState } from "./WorkflowRunState";

export type WorkflowRun = { id: string, workflowId: string, workflowName: string, executionMode: WorkflowExecutionMode, workingDir: string, state: WorkflowRunState, definitionSnapshot: WorkflowDef, steps: Array<StepRun>, createdAt: string, updatedAt: string, completedAt: string | null, };
