import type { ToolKind } from './types'

export const allTools: ToolKind[] = [
  'claude',
  'codex',
  'openClaw',
  'hermes',
  'codeBuddy',
  'gemini',
  'pi',
  'openCode',
  'copilot',
  'openHands',
  'continueCn',
  'qwen',
  'kimi',
  'goose',
  'cursor',
  'cline',
  'kiro',
  'workBuddy',
  'amazonQ',
  'aider',
  'amp',
  'windsurf',
  'codebuff',
  'roo',
  'kilo',
]

/** Title-case labels for each tool/source, suitable for prose or mixed-case UI. */
export const sourceLabels: Record<ToolKind, string> = {
  claude: 'Claude Code',
  codex: 'Codex',
  openClaw: 'OpenClaw',
  hermes: 'Hermes',
  codeBuddy: 'CodeBuddy',
  gemini: 'Gemini CLI',
  pi: 'Pi Agent',
  openCode: 'opencode',
  copilot: 'GitHub Copilot',
  openHands: 'OpenHands',
  continueCn: 'Continue cn',
  qwen: 'Qwen Code',
  kimi: 'Kimi Code',
  goose: 'Goose',
  cursor: 'Cursor Agent',
  cline: 'Cline',
  kiro: 'Kiro',
  workBuddy: 'WorkBuddy',
  amazonQ: 'Amazon Q',
  aider: 'Aider',
  amp: 'Amp',
  windsurf: 'Windsurf',
  codebuff: 'Codebuff',
  roo: 'Roo Code',
  kilo: 'Kilo Code',
}

/** Upper-case labels for section headers and stat tables. */
export const sourceLabelsUpper: Record<ToolKind, string> = {
  claude: 'CLAUDE CODE',
  codex: 'CODEX',
  openClaw: 'OPENCLAW',
  hermes: 'HERMES',
  codeBuddy: 'CODEBUDDY',
  gemini: 'GEMINI CLI',
  pi: 'PI AGENT',
  openCode: 'OPENCODE',
  copilot: 'GITHUB COPILOT',
  openHands: 'OPENHANDS',
  continueCn: 'CONTINUE CN',
  qwen: 'QWEN CODE',
  kimi: 'KIMI CODE',
  goose: 'GOOSE',
  cursor: 'CURSOR AGENT',
  cline: 'CLINE',
  kiro: 'KIRO',
  workBuddy: 'WORKBUDDY',
  amazonQ: 'AMAZON Q',
  aider: 'AIDER',
  amp: 'AMP',
  windsurf: 'WINDSURF',
  codebuff: 'CODEBUFF',
  roo: 'ROO CODE',
  kilo: 'KILO CODE',
}
